import express from "express";
import { redirectToLogin } from "./middleware/redirectToLogin";
import { router } from "./routes/route";
import { staticroute } from "./routes/static.route";
import { urlRouter } from "./routes/url.route";
const cookieParser = require("cookie-parser");
const path = require("path");
require("dotenv").config();
const app = express();
app.set("view engine", "ejs");
app.set("views", path.resolve("./views"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use("/api/url", urlRouter);
app.use("/api/admin/users", redirectToLogin, staticroute);
app.use("/api", router);
app.use("/api", staticroute);

app.listen(8000, () => console.log("Server is listening on port 8000"));
